name: sprightly_inventory
description: Private, Free & Open Source Inventory Manager
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.2.0 <3.0.0'

dependencies:
  # Look & Feel
  cupertino_icons: ^1.0.3

  # submodule
  dart_marganam:
    path: ../dart_marganam

  # drift-sqlite, previously moor-sqlite
  drift: ^1.1.0

  equatable: ^2.0.3

  flutter:
    sdk: flutter

  # DI
  json_annotation: ^4.4.0
  kiwi: ^3.0.0

  # package information
  package_info_plus: ^1.0.6

  # path
  path: ^1.8.0

  # sqlite3-moor
  sqlite3_flutter_libs: ^0.5.2

dev_dependencies:
  build_runner: ^2.1.5
  drift_dev: ^1.1.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.1
  lint: ^1.8.1
  # mockito: ^5.0.14

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - assets/queries_min/ # custom & complex sql queries
    - assets/i18n/ # internationalization (i18n) & language support
    - assets/config/ # app_config(AppConfig) configuration files
